theme: jekyll-theme-cayman
title: Test title
description: test description
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"